# Generated by Django 4.2.4 on 2023-08-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("postTitle", models.CharField(max_length=255)),
                ("postContent", models.CharField(max_length=255)),
                (
                    "postOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="BLOG.bloguser"
                    ),
                ),
            ],
        ),
    ]
