# Generated by Django 4.2.4 on 2023-08-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0002_alter_bloguser_id_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="postOwner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="BLOG.bloguser",
            ),
        ),
    ]
