# Generated by Django 4.2.4 on 2023-08-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BLOG", "0003_alter_post_postowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Hirer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jobTitle", models.CharField(max_length=255)),
                ("jobDescription", models.CharField(max_length=255)),
                (
                    "jobOwner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BLOG.hirer",
                    ),
                ),
            ],
        ),
    ]
